<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.23" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.23" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.23" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.23" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.23" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CamelRegistry.Logic\CamelRegistry.Logic.csproj" />
    <ProjectReference Include="..\CamelRegistry.Repository\CamelRegistry.Repository.csproj" />
  </ItemGroup>

</Project>
