// <auto-generated />
using System;
using CamelRegistry.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CamelRegistry.Repository.Migrations
{
    [DbContext(typeof(CamelDbContext))]
    [Migration("20260208155147_dump_data")]
    partial class dump_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("CamelRegistry.Entities.Camel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("HumpCount")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Camels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69e78efa-c4dd-4379-bfa3-65a7db97996f"),
                            Color = "Brown",
                            HumpCount = 2,
                            LastFed = new DateTime(2026, 2, 8, 16, 51, 46, 653, DateTimeKind.Local).AddTicks(9135),
                            Name = "Default Camel"
                        },
                        new
                        {
                            Id = new Guid("43004233-b9bf-487c-ba55-37b8ac938392"),
                            Color = "Brown",
                            HumpCount = 1,
                            LastFed = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Default Camel2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
